### PR TITLE
Keeping RPIP-49 up to date.

### PR DESCRIPTION
**Pull request by LongForWisdom**

### CODE REVIEW

**Comment by Valdorff** [comment]
Maybe we should swap to checkmarks? That way 1 and 3 can be shown as done and 2/4 as ongoing?

**Comment by LongForWisdom** [comment]
> Maybe we should swap to checkmarks? That way 1 and 3 can be shown as done and 2/4 as ongoing?

Sure, lets find out if checkmarks work lol.

**Comment by LongForWisdom** [comment]
They do not. Went with this:
image

**Review by Valdorff — APPROVED** [review]
ty!

**Pull request merged**
