### PR TITLE
Improved Reference Implementation with Kane's feedback

### PR DESCRIPTION
**Pull request by Valdorff**

### CODE REVIEW

**Comment by Valdorff** [comment]
Community has been asked for comments/review

**Review by htimsk — APPROVED** [review]
Fell free to accept or reject the suggested edits.

**Comment by Valdorff** [comment]
> Fell free to accept or reject the suggested edits.
Kept almost all of it except one edit.

Also realized one sentence was outdated after Kane's help and just deleted it.

**Comment by xrchz** [comment]
LGTM

**Pull request merged**
